// Generated by puzzlescript_cpp specialize-rulegroups. Do not edit by hand.
#include <cstdint>
#include "runtime/compiled_rules.hpp"

extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_dd084f079040a474();
extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_7748a6730cb1e015();
extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_8e1fb965280a8309();
extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_4f10b5618ae1b995();
extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_3f2f5c7e63747a7b();
extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_a642b70ee5b99db9();
extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_f8a00c14d3a36ec5();
extern "C" const puzzlescript::SpecializedCompactTurnBackend* solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_67e406108f631fee();

extern "C" const puzzlescript::SpecializedRulegroupsBackend* ps_specialized_rulegroups_find_backend(uint64_t sourceHash) {
    (void)sourceHash;
    return nullptr;
}

extern "C" const puzzlescript::SpecializedRulegroupsBackend* ps_compiled_rules_find_backend(uint64_t sourceHash) {
    return ps_specialized_rulegroups_find_backend(sourceHash);
}

extern "C" const puzzlescript::SpecializedFullTurnBackend* ps_specialized_full_turn_find_backend(uint64_t sourceHash) {
    (void)sourceHash;
    return nullptr;
}

extern "C" const puzzlescript::SpecializedFullTurnBackend* ps_compiled_tick_find_backend(uint64_t sourceHash) {
    return ps_specialized_full_turn_find_backend(sourceHash);
}

extern "C" const puzzlescript::SpecializedCompactTurnBackend* ps_specialized_compact_turn_find_backend(uint64_t sourceHash) {
    switch (sourceHash) {
        case 15927066976099279988ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_dd084f079040a474();
        case 8595302901901025301ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_7748a6730cb1e015();
        case 10241107921778410249ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_8e1fb965280a8309();
        case 5697252959170181525ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_4f10b5618ae1b995();
        case 4552959446199073403ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_3f2f5c7e63747a7b();
        case 11980339233370512825ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_a642b70ee5b99db9();
        case 17915332601269415621ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_f8a00c14d3a36ec5();
        case 7486115148791488494ULL: return solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_specialized_compact_turn_backend_67e406108f631fee();
        default: return nullptr;
    }
}

extern "C" const puzzlescript::SpecializedCompactTurnBackend* ps_compiled_compact_tick_find_backend(uint64_t sourceHash) {
    return ps_specialized_compact_turn_find_backend(sourceHash);
}

extern "C" const uint32_t solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_compiled_rule_count = 0U;
extern "C" const uint32_t solver_timeout_curve_3366d476044c5ccc13eb2e5994d26c568a179281eb0d2301209deab0ad4a5e73_compiled_group_count = 0U;
