import {
  acceptCompletion,
  autocompletion,
  closeCompletion,
  completionStatus,
  currentCompletions,
  moveCompletionSelection,
  setSelectedCompletion,
  startCompletion
} from "@codemirror/autocomplete"
import {
  cursorCharLeft,
  cursorCharRight,
  cursorDocEnd,
  cursorDocStart,
  cursorGroupLeft,
  cursorGroupRight,
  cursorLineBoundaryBackward,
  cursorLineBoundaryForward,
  cursorLineBoundaryLeft,
  cursorLineBoundaryRight,
  cursorLineDown,
  cursorLineEnd,
  cursorLineStart,
  cursorLineUp,
  cursorPageDown,
  cursorPageUp,
  deleteCharBackward,
  deleteCharForward,
  deleteGroupBackward,
  deleteGroupForward,
  deleteLineBoundaryBackward,
  deleteLineBoundaryForward,
  deleteToLineEnd,
  history,
  indentLess,
  indentMore,
  insertNewlineAndIndent,
  insertTab,
  isolateHistory,
  redo,
  redoSelection,
  selectAll,
  selectCharLeft,
  selectCharRight,
  selectDocEnd,
  selectDocStart,
  selectGroupLeft,
  selectGroupRight,
  selectLineBoundaryBackward,
  selectLineBoundaryForward,
  selectLineBoundaryLeft,
  selectLineBoundaryRight,
  selectLineDown,
  selectLineEnd,
  selectLineStart,
  selectLineUp,
  selectPageDown,
  selectPageUp,
  splitLine,
  transposeChars,
  undo,
  undoSelection
} from "@codemirror/commands"
import {
  ensureSyntaxTree,
  getIndentUnit,
  StreamLanguage,
  StringStream,
  syntaxTree,
  syntaxTreeAvailable
} from "@codemirror/language"
import {
  SearchQuery,
  closeSearchPanel,
  findNext,
  findPrevious,
  getSearchQuery,
  openSearchPanel,
  replaceAll,
  search,
  setSearchQuery
} from "@codemirror/search"
import {
  EditorSelection,
  EditorState,
  StateEffect,
  StateField,
  Text,
  Transaction
} from "@codemirror/state"
import {
  Decoration,
  EditorView,
  ViewPlugin,
  drawSelection,
  dropCursor,
  highlightActiveLine,
  highlightActiveLineGutter,
  keymap,
  lineNumbers
} from "@codemirror/view"
import {Tree} from "@lezer/common"
import {Tag} from "@lezer/highlight"

const runtime = Object.freeze({
  versions: Object.freeze(__PUZZLESCRIPT_CM6_VERSIONS__),
  acceptCompletion,
  autocompletion,
  closeCompletion,
  completionStatus,
  currentCompletions,
  moveCompletionSelection,
  setSelectedCompletion,
  startCompletion,
  cursorCharLeft,
  cursorCharRight,
  cursorDocEnd,
  cursorDocStart,
  cursorGroupLeft,
  cursorGroupRight,
  cursorLineBoundaryBackward,
  cursorLineBoundaryForward,
  cursorLineBoundaryLeft,
  cursorLineBoundaryRight,
  cursorLineDown,
  cursorLineEnd,
  cursorLineStart,
  cursorLineUp,
  cursorPageDown,
  cursorPageUp,
  deleteCharBackward,
  deleteCharForward,
  deleteGroupBackward,
  deleteGroupForward,
  deleteLineBoundaryBackward,
  deleteLineBoundaryForward,
  deleteToLineEnd,
  history,
  indentLess,
  indentMore,
  insertNewlineAndIndent,
  insertTab,
  isolateHistory,
  redo,
  redoSelection,
  selectAll,
  selectCharLeft,
  selectCharRight,
  selectDocEnd,
  selectDocStart,
  selectGroupLeft,
  selectGroupRight,
  selectLineBoundaryBackward,
  selectLineBoundaryForward,
  selectLineBoundaryLeft,
  selectLineBoundaryRight,
  selectLineDown,
  selectLineEnd,
  selectLineStart,
  selectLineUp,
  selectPageDown,
  selectPageUp,
  splitLine,
  transposeChars,
  undo,
  undoSelection,
  ensureSyntaxTree,
  getIndentUnit,
  StreamLanguage,
  StringStream,
  syntaxTree,
  syntaxTreeAvailable,
  SearchQuery,
  closeSearchPanel,
  findNext,
  findPrevious,
  getSearchQuery,
  openSearchPanel,
  replaceAll,
  search,
  setSearchQuery,
  EditorSelection,
  EditorState,
  StateEffect,
  StateField,
  Text,
  Transaction,
  Decoration,
  EditorView,
  ViewPlugin,
  drawSelection,
  dropCursor,
  highlightActiveLine,
  highlightActiveLineGutter,
  keymap,
  lineNumbers,
  Tree,
  Tag
})

if (globalThis.PuzzleScriptCM6Runtime) {
  throw new Error("PuzzleScriptCM6Runtime is already installed")
}
globalThis.PuzzleScriptCM6Runtime = runtime
