#!/usr/bin/env node
'use strict';

/**
 * Classify testdata.js simulation fixtures by JS compile diagnostics and write
 * Lean "clean kernel" candidate names (no errors, no warnings).
 *
 * Usage (repo root):
 *   node scripts/lean_clean_sim_candidates.js
 *   node scripts/lean_clean_sim_candidates.js --out lean/parity_clean_candidates.txt
 */

const fs = require('fs');
const path = require('path');

const { loadPuzzleScript } = require('../src/tests/js_oracle/lib/puzzlescript_node_env');

function parseArgs(argv) {
    const args = argv.slice(2);
    let outPath = path.resolve('lean/parity_clean_candidates.txt');
    let summaryPath = path.resolve('build/lean-clean-sim-summary.json');
    for (let i = 0; i < args.length; i++) {
        const arg = args[i];
        if (arg === '--out' && args[i + 1]) {
            outPath = path.resolve(args[++i]);
        } else if (arg === '--summary' && args[i + 1]) {
            summaryPath = path.resolve(args[++i]);
        } else if (arg === '--help' || arg === '-h') {
            console.log(`Usage: node scripts/lean_clean_sim_candidates.js [--out path] [--summary path]

Clean = JS compile of the simulation fixture source yields errorCount === 0
and no entries in errorStrings (warnings are stored there too).
`);
            process.exit(0);
        } else {
            console.error(`Unknown argument: ${arg}`);
            process.exit(2);
        }
    }
    return { outPath, summaryPath };
}

function resetDiagnostics() {
    if (typeof resetParserErrorState === 'function') {
        resetParserErrorState();
    } else {
        errorStrings = [];
        errorCount = 0;
    }
}

function classifySimulationEntry(entry) {
    const [name, payload] = entry;
    const source = payload[0];
    const targetLevel = payload[3] === undefined ? 0 : payload[3];
    const randomSeed = payload[4] === undefined ? null : payload[4];

    resetDiagnostics();
    unitTesting = true;
    lazyFunctionGeneration = false;
    let threw = null;
    try {
        compile(['loadLevel', targetLevel], `${source}\n`, randomSeed);
    } catch (e) {
        threw = e && e.message ? e.message : String(e);
    } finally {
        unitTesting = false;
        lazyFunctionGeneration = true;
    }

    const strings = Array.isArray(errorStrings) ? errorStrings.slice() : [];
    const count = typeof errorCount === 'number' ? errorCount : 0;
    const hasWarnings = strings.some((s) => /warningText/i.test(String(s)));
    const hasErrorText = strings.some((s) => /errorText/i.test(String(s)));

    let status;
    if (threw !== null || count > 0 || hasErrorText) {
        status = 'error';
    } else if (strings.length > 0 || hasWarnings) {
        status = 'warning';
    } else {
        status = 'clean';
    }

    return {
        name,
        status,
        errorCount: count,
        diagnosticCount: strings.length,
        threw,
    };
}

function main() {
    const { outPath, summaryPath } = parseArgs(process.argv);
    loadPuzzleScript({ includeTests: true });

    if (!Array.isArray(global.testdata)) {
        console.error('testdata.js did not populate global.testdata');
        process.exit(1);
    }

    const results = global.testdata.map(classifySimulationEntry);
    const clean = results.filter((r) => r.status === 'clean').map((r) => r.name);
    const warning = results.filter((r) => r.status === 'warning').map((r) => r.name);
    const error = results.filter((r) => r.status === 'error').map((r) => r.name);

    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    // Use ## for comments: some fixture names begin with a single '#' (e.g. "#1067 ...").
    fs.writeFileSync(
        outPath,
        [
            '## Auto-generated by scripts/lean_clean_sim_candidates.js',
            '## Simulation fixtures that JS-compile with zero errors and zero warnings.',
            '## Lean parity_whitelist.txt entries should be drawn from this list.',
            '',
            ...clean,
            '',
        ].join('\n'),
        'utf8'
    );

    fs.mkdirSync(path.dirname(summaryPath), { recursive: true });
    const summary = {
        schema_version: 1,
        generated_at: new Date().toISOString(),
        total: results.length,
        clean_count: clean.length,
        warning_count: warning.length,
        error_count: error.length,
        clean,
        warning,
        error,
        results,
    };
    fs.writeFileSync(summaryPath, `${JSON.stringify(summary, null, 2)}\n`, 'utf8');

    console.log(`lean clean sim candidates: ${clean.length} clean / ${warning.length} warning / ${error.length} error (total ${results.length})`);
    console.log(`wrote ${outPath}`);
    console.log(`wrote ${summaryPath}`);
}

main();
